name: Go Nancy

on:
    # Scan changed files in PRs (diff-aware scanning):
    pull_request: {}
    # Scan on-demand through GitHub Actions interface:
    workflow_dispatch: {}
    # Scan mainline branches and report all findings:
    push:
      branches: ["master", "develop"]

jobs:
  build:
    strategy:
        matrix:
          go-version: [1.24.x]
          os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Set up Go 1.x in order to write go.list file
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    
    - name: Go mod tidy
      run: go mod tidy

    - name: WriteGoList
      run:  go list -json -deps ./... > go.list

    - name: Nancy
       run: |
        echo "Running Nancy (sleuth --loud)..."
        if ! command -v nancy >/dev/null 2>&1; then
           curl -sSL -o nancy https://github.com/sonatype-nexus-community/nancy/releases/download/v1.0.52/nancy_1.0.52_linux_amd64
        chmod +x nancy && sudo mv nancy /usr/local/bin/nancy
        fi
        go list -json -deps ./... | nancy sleuth --loud
    
